user:
	goctl model mysql ddl -src sql/user.sql -dir .

comment:
	goctl model mysql ddl -src sql/comment.sql -dir .

relation:
	goctl model mysql ddl -src sql/relation.sql -dir .

video:
	goctl model mysql ddl -src sql/video.sql -dir .