api:
	goctl api go -api system.api -dir ./
	goctl api plugin -plugin goctl-swagger="swagger --filename api-swagger.json" --api system.api -dir .


#api-swagger:
#	goctl api plugin -plugin goctl-swagger="swagger --filename api-swagger.json" --api system.api -dir .