// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"go-zeroTiktok/relation-service/internal/logic"
	"go-zeroTiktok/relation-service/internal/svc"
	"go-zeroTiktok/relation-service/pb/relation"
)

type RelationServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedRelationServer
}

func NewRelationServer(svcCtx *svc.ServiceContext) *RelationServer {
	return &RelationServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServer) Action(ctx context.Context, in *relation.ActionReq) (*relation.ActionResp, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *RelationServer) FollowList(ctx context.Context, in *relation.FollowListReq) (*relation.FollowListResp, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *RelationServer) FollowerList(ctx context.Context, in *relation.FollowerListReq) (*relation.FollowerListResp, error) {
	l := logic.NewFollowerListLogic(ctx, s.svcCtx)
	return l.FollowerList(in)
}
