// Code generated by goctl. DO NOT EDIT.
// Source: publish.proto

package server

import (
	"context"

	"go-zeroTiktok/publish-service/internal/logic"
	"go-zeroTiktok/publish-service/internal/svc"
	"go-zeroTiktok/publish-service/pb/publish"
)

type PublishServer struct {
	svcCtx *svc.ServiceContext
	publish.UnimplementedPublishServer
}

func NewPublishServer(svcCtx *svc.ServiceContext) *PublishServer {
	return &PublishServer{
		svcCtx: svcCtx,
	}
}

func (s *PublishServer) Action(ctx context.Context, in *publish.ActionReq) (*publish.ActionResp, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *PublishServer) List(ctx context.Context, in *publish.ListReq) (*publish.ListResp, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}
