// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package server

import (
	"context"

	"go-zeroTiktok/favorite-service/internal/logic"
	"go-zeroTiktok/favorite-service/internal/svc"
	"go-zeroTiktok/favorite-service/pb/favorite"
)

type FavoriteServer struct {
	svcCtx *svc.ServiceContext
	favorite.UnimplementedFavoriteServer
}

func NewFavoriteServer(svcCtx *svc.ServiceContext) *FavoriteServer {
	return &FavoriteServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteServer) CreateFavorite(ctx context.Context, in *favorite.CreateFavoriteReq) (*favorite.CreateFavoriteResp, error) {
	l := logic.NewCreateFavoriteLogic(ctx, s.svcCtx)
	return l.CreateFavorite(in)
}

func (s *FavoriteServer) CancelFavorite(ctx context.Context, in *favorite.CancelFavoriteReq) (*favorite.CancelFavoriteResp, error) {
	l := logic.NewCancelFavoriteLogic(ctx, s.svcCtx)
	return l.CancelFavorite(in)
}

func (s *FavoriteServer) GetFavoriteList(ctx context.Context, in *favorite.FavoriteList) (*favorite.FavoriteListResp, error) {
	l := logic.NewGetFavoriteListLogic(ctx, s.svcCtx)
	return l.GetFavoriteList(in)
}
