// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	UserName string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type RegisterResp struct {
	StatusCode int8   `json:"status_code"` // 状态码 0-成功 1-失败
	StatusMsg  string `json:"status_msg"`  // 状态信息
	UserId     int64  `json:"user_id"`     // 用户id
	Token      string `json:"token"`       // token
}

type LoginReq struct {
	UserName string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	StatusCode int8   `json:"status_code"` // 状态码 0-成功 1-失败
	StatusMsg  string `json:"status_msg"`  // 状态信息
	UserId     int64  `json:"user_id"`     // 用户id
	Token      string `json:"token"`       // token
}

type User struct {
	Id            int64  `json:"id"`             // 用户id
	Name          string `json:"name"`           // 用户名
	FollowCount   int64  `json:"follow_count"`   // 关注数
	FollowerCount int64  `json:"follower_count"` // 粉丝数
	IsFollow      bool   `json:"is_follow"`      // 是否关注
}

type UserReq struct {
	UserId int64 `json:"user_id"` // 用户id
}

type UserResp struct {
	StatusCode int8   `json:"status_code"` // 状态码 0-成功 1-失败
	StatusMsg  string `json:"status_msg"`  // 状态信息
	User       User   `json:"user"`        // 用户信息
}
